import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models.dart';

/// Builds a "Class Routine" PDF that mirrors the in-app look:
/// transparent fills, leaf-green @ 30% alpha grid borders, and a centered
/// "—" for empty slots.
class RoutinePdf {
  static const _leafGreen30 = PdfColor.fromInt(0x4D43A047); // 30% alpha green
  static const _leafGreen = PdfColor.fromInt(0xFF43A047);
  static const _muted = PdfColor.fromInt(0xFF8A8A8A);
  static const _ink = PdfColor.fromInt(0xFF222222);

  static const _daysShort = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  static const _daysLong = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
  ];

  static Future<Uint8List> build(
    List<ClassItem> routine, {
    List<Subject> subjects = const [],
  }) async {
    // Group classes by weekday, preserving their list order (= position).
    final byDay = <int, List<ClassItem>>{
      for (var i = 1; i <= 7; i++) i: <ClassItem>[],
    };
    for (final c in routine) {
      byDay[c.weekday]?.add(c);
    }
    final teacherBySubject = <String, String>{
      for (final s in subjects) s.name.toLowerCase(): s.teacher.trim(),
    };
    final maxN = byDay.values.fold<int>(0, (a, b) => a > b.length ? a : b.length);
    final cols = maxN < 1 ? 1 : maxN;

    // Landscape when the table gets wide enough that portrait would crush it.
    final pageFormat =
        cols >= 6 ? PdfPageFormat.a4.landscape : PdfPageFormat.a4;
    final generatedAt = DateFormat('d MMM y, HH:mm').format(DateTime.now());

    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: pageFormat,
        margin: const pw.EdgeInsets.fromLTRB(28, 32, 28, 28),
        footer: (ctx) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by BunkSafe',
                style: pw.TextStyle(fontSize: 9, color: _muted),
              ),
              pw.Text(
                'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                style: pw.TextStyle(fontSize: 9, color: _muted),
              ),
            ],
          ),
        ),
        build: (ctx) => [
          _header(generatedAt),
          pw.SizedBox(height: 14),
          _table(byDay, cols, teacherBySubject),
        ],
      ),
    );
    return doc.save();
  }

  static pw.Widget _header(String generatedAt) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.end,
          children: [
            pw.Text(
              'BunkSafe',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: _leafGreen,
                letterSpacing: 0.4,
              ),
            ),
            pw.SizedBox(width: 8),
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 2),
              child: pw.Text(
                '· Class Routine',
                style: pw.TextStyle(
                  fontSize: 13,
                  color: _ink,
                  fontWeight: pw.FontWeight.normal,
                ),
              ),
            ),
            pw.Spacer(),
            pw.Text(
              generatedAt,
              style: pw.TextStyle(fontSize: 10, color: _muted),
            ),
          ],
        ),
        pw.SizedBox(height: 6),
        pw.Container(height: 1.2, color: _leafGreen30),
      ],
    );
  }

  static pw.Widget _table(
    Map<int, List<ClassItem>> byDay,
    int cols,
    Map<String, String> teacherBySubject,
  ) {
    final columnWidths = <int, pw.TableColumnWidth>{
      0: const pw.FlexColumnWidth(1.0),
      for (var i = 1; i <= cols; i++) i: const pw.FlexColumnWidth(1.6),
    };

    return pw.Table(
      border: pw.TableBorder.all(color: _leafGreen30, width: 1.0),
      defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
      columnWidths: columnWidths,
      children: [
        // Header row.
        pw.TableRow(
          children: [
            _headCell('Day'),
            for (var i = 1; i <= cols; i++) _headCell('$i'),
          ],
        ),
        // One row per weekday.
        for (var w = 1; w <= 7; w++)
          pw.TableRow(
            children: [
              _dayCell(w),
              for (var i = 0; i < cols; i++)
                _classCell(
                  i < byDay[w]!.length ? byDay[w]![i].subject : null,
                  i < byDay[w]!.length
                      ? teacherBySubject[byDay[w]![i].subject.toLowerCase()]
                      : null,
                ),
            ],
          ),
      ],
    );
  }

  static pw.Widget _headCell(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      alignment: pw.Alignment.center,
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
          color: _leafGreen,
          letterSpacing: 0.6,
        ),
      ),
    );
  }

  static pw.Widget _dayCell(int weekday) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 10),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text(
            _daysShort[weekday - 1],
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: _ink,
            ),
          ),
          pw.SizedBox(height: 1),
          pw.Text(
            _daysLong[weekday - 1],
            style: pw.TextStyle(fontSize: 8, color: _muted),
          ),
        ],
      ),
    );
  }

  static pw.Widget _classCell(String? subject, String? teacher) {
    final empty = subject == null || subject.trim().isEmpty;
    if (empty) {
      return pw.Container(
        height: 28,
        padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 10),
      );
    }
    final hasTeacher = teacher != null && teacher.trim().isNotEmpty;
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 10),
      alignment: pw.Alignment.center,
      child: pw.Column(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text(
            subject,
            textAlign: pw.TextAlign.center,
            maxLines: hasTeacher ? 1 : 2,
            style: pw.TextStyle(
              fontSize: 10.5,
              fontWeight: pw.FontWeight.bold,
              color: _ink,
            ),
          ),
          if (hasTeacher) ...[
            pw.SizedBox(height: 2),
            pw.Text(
              teacher.trim(),
              textAlign: pw.TextAlign.center,
              maxLines: 1,
              style: pw.TextStyle(
                fontSize: 9,
                color: _muted,
              ),
            ),
          ],
        ],
      ),
    );
  }
}
